lab5/Models/ViewModels/RentsViewModel.cs
using IGILab1Norm;
using lab2.Models.Filters;
using lab2.Models.Sorts;
using lab2.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace lab2.Models
{
    public class RentsViewModel
    {
        public IEnumerable<Rent> Rents { get; set; }
        public RentFilter RentFilter { get; set; }
        public RentSort RentSort { get; set; }
        public PageViewModel PageViewModel { get; set; }

        public RentsViewModel()
        {
            RentFilter = new RentFilter();
            RentSort = new RentSort();
        }
    }
}

lab5/Controllers/RentController.cs
using IGILab1Norm;
using lab2.Extensions;
using lab2.Extensions.Filters;
using lab2.Models;
using lab2.Models.Filters;
using lab2.Models.Sorts;
using lab2.Models.ViewModels;
using lab2.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace lab2.Controllers
{
    [LoggerFilter]
    [ExceptionFilter]
    [Authorize(Roles = "admin")]
    public class RentController : Controller
    {
        private RentContext _db;

        public RentController(RentContext db)
        {
            _db = db;
        }

        [HttpPost]
        [SetToSession("Rent filter")]
        public IActionResult Index(RentFilter rentFilter, int page = 1)
        {
            RentsViewModel viewModel = new RentsViewModel();

            var sessionSort = HttpContext.Session.Get("Rent sort");
            if (sessionSort != null && sessionSort.Count > 0)
            {
                RentSort.State currentSort = (RentSort.State)Enum.Parse(typeof(RentSort.State), sessionSort["sortState"]);
                HttpContext.Session.Set("Rent sort", currentSort);
                viewModel.RentSort = new RentSort(currentSort);
            }
            viewModel.RentFilter = rentFilter;

            SetRents(viewModel, page);

            return View(viewModel);
        }

        [HttpGet]
        [SetToSession("Rent sort")]
        public IActionResult Index(RentSort.State sortState = RentSort.State.None, int page = 1)
        {
            RentsViewModel viewModel = new RentsViewModel();

            var sessionFilter = HttpContext.Session.Get("Rent filter");
            var sessionSort = HttpContext.Session.Get("Rent sort");
            RentSort.State currentSort = RentSort.State.None;
            if (sessionSort != null && sessionSort.Count > 0)
            {
                currentSort = (RentSort.State)Enum.Parse(typeof(RentSort.State), sessionSort["sortState"]);
                HttpContext.Session.Set("Rent sort", currentSort);
                viewModel.RentSort = new RentSort(currentSort);
            }
            if (sessionFilter != null)
            {
                viewModel.RentFilter = Converter.DictionaryToObject<RentFilter>(sessionFilter);
                HttpContext.Session.Set("Rent filter",viewModel.RentFilter);
            }
            if (sortState == RentSort.State.None && currentSort != RentSort.State.None)
                sortState = currentSort;
            viewModel.RentSort = new RentSort(sortState);

            SetRents(viewModel, page);

            return View(viewModel);
        }

        private void SetRents(RentsViewModel viewModel, int page)
        {
            var rents = _db.Rents.ToList();
            int pageSize = 15;
            switch (viewModel.RentSort.Models.CurrentSort)
            {
                case RentSort.State.DateGetAsc:
                    rents = rents.OrderBy(t => t.DateGet).ToList();
                    break;
                case RentSort.State.DateGetDesc:
                    rents = rents.OrderByDescending(t => t.DateGet).ToList();
                    break;
                case RentSort.State.RentDateAsc:
                    rents = rents.OrderBy(t => t.RentDate).ToList();
                    break;
                case RentSort.State.RentDateDesc:
                    rents = rents.OrderByDescending(t => t.RentDate).ToList();
                    break;
                case RentSort.State.WorkerFIOAsc:
                    rents = rents.OrderBy(t => t.WorkerFIO).ToList();
                    break;
                case RentSort.State.WorkerFIODesc:
                    rents = rents.OrderByDescending(t => t.WorkerFIO).ToList();
                    break;
            }

            try
            {
                string strMonth = viewModel.RentFilter.MonthRent;
                if (!String.IsNullOrEmpty(strMonth))
                {
                    int month = Int32.Parse(strMonth);
                    rents = rents.Where(t => t.RentDate.Month == month).ToList();
                }
            }
            catch (Exception ex)
            {

            }
            string workerFIO = viewModel.RentFilter.WorkerFIO;
            if (workerFIO != null)
                rents = rents.Where(t => t.WorkerFIO.Contains(workerFIO)).ToList();

            var count = rents.Count;
            var items = rents.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);

            viewModel.PageViewModel = pageViewModel;
            viewModel.Rents = items;
            Rent rent = new Rent();
            ViewData["AddingRent"] = rent;
            ViewData["Cars"] = _db.Cars.ToList();
            ViewData["Clients"] = _db.Clients.ToList();
        }

        [HttpPost]
        public IActionResult AddNewRent(Rent rent, int client, int car)
        {
            rent.CarID = car;
            rent.Car = _db.Cars.Where(x => x.CarID == car).FirstOrDefault();
            rent.ClientID = client;
            rent.Client = _db.Clients.Where(x => x.Id == client).FirstOrDefault();
            _db.Rents.Add(rent);
            _db.SaveChanges();
            return Redirect("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var item = _db.Rents.Where(x => x.RentID == id).FirstOrDefault();
            _db.Rents.Remove(item);
            _db.SaveChanges();

            return Redirect("Index");
        }

        [HttpPost]
        public IActionResult SaveChanges(Rent rent, int client, int car)
        {
            rent.CarID = car;
            rent.Car = _db.Cars.Where(x => x.CarID == car).FirstOrDefault();
            rent.ClientID = client;
            rent.Client = _db.Clients.Where(x => x.Id == client).FirstOrDefault();
            _db.Rents.Update(rent);
            _db.SaveChanges();
            return Redirect("Index");
        }


        [HttpPost]
        public IActionResult Edit(int id)
        {
            var item = _db.Rents.Where(x => x.RentID == id).FirstOrDefault();
            ViewData["Cars"] = _db.Cars.ToList();
            ViewData["Clients"] = _db.Clients.ToList();

            return View(item);
        }
    }
}

lab5/Views/Rent/Edit.cshtml
@model IGILab1Norm.Rent
@using IGILab1Norm

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (@Html.BeginForm("SaveChanges", "Rent", FormMethod.Post))
{
    <input type="hidden" value="@Model.RentID" name="RentID" />
    <div class="form-group">
        <label for="Clients">Select client</label>
        <select class="form-control" id="Client" name="Client" >
            @{
                List<Client> clients = (List<Client>)ViewData["Clients"];
                Client currentClient = clients.Where(x => x.Id == Model.ClientID).First();
                clients.Remove(currentClient);
                clients.Insert(0, currentClient);
                foreach (var item in clients)
                {
                    <option value=@item.Id>
                        @item.ClienFIO
                    </option>

                }
            }
        </select>
    </div>
    <div class="form-group">
        <label for="Car">Select car</label>
        <select class="form-control" id="Car" name="Car">
            @{
                List<Car> cars = (List<Car>)ViewData["Cars"];
                Car currentCar = cars.Where(x => x.CarID == Model.CarID).First();
                cars.Remove(currentCar);
                cars.Insert(0, currentCar);
                foreach (var item in cars)
                {
                    <option value=@item.CarID>
                        @item.CarMark @item.RegNum
                    </option>

                }
            }
        </select>
    </div>
    <div class="form-group">
        <label for="RentDate">Input rent date</label>

        @Html.EditorFor(model => Model.RentDate)
    </div>
    <div class="form-group">
        <label for="DateGet">Input date get</label>

        @Html.EditorFor(model => Model.DateGet)
    </div>
    <div class="form-group">
        <label for="RentPrice">Input rent price</label>

        @Html.EditorFor(model => Model.RentPrice)
    </div>
    <div class="form-group">
        <label for="Paid">Input is paid</label>

        @Html.EditorFor(model => Model.Paid)
    </div>
    <div class="form-group">
        <label for="WorkerFIO">Input worker fio</label>

        @Html.EditorFor(model => Model.WorkerFIO)
    </div>
    <input type="submit" />

}

lab5/Views/Rent/Index.cshtml
@{
    ViewData["Title"] = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model RentsViewModel
@using lab2.Models
@using IGILab1Norm;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div style="border:double grey 4px; margin-top:5px; padding:20px; padding-bottom:20px; ">
    <form asp-action="Index" class="form-inline" method="post" style=" width:600px;margin:0px auto;">
        Month of rent: @Html.TextBox("MonthRent", Model.RentFilter.MonthRent)
        Worker FIO: @Html.TextBox("WorkerFIO", Model.RentFilter.WorkerFIO)
        <input type="submit" value="Find" />
    </form>
    <table style="width:100%; border:4px double; padding:20px; ">
        <tr>
            <th>ID</th>
            <th>
                <a asp-action="Index" asp-route-sortState="@Model.RentSort.Models.RentDateSort">
                    Rent date
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortState="@Model.RentSort.Models.DateGetSort">
                    Date get
                </a>
            </th>
            <th>Car ID</th>
            <th>Client ID</th>
            <th>Rent price</th>
            <th>is Paid</th>
            <th>
                <a asp-action="Index" asp-route-sortState="@Model.RentSort.Models.WorkerFIOSort">
                    Worker FIO
                </a>
            </th>
            <th>

            </th>
        </tr>
        @foreach (Rent current in Model.Rents)
        {
            <tr>
                <td>@current.RentID</td>
                <td>@current.RentDate.ToString("yyyy-MM-dd")</td>
                <td>@current.DateGet.ToString("yyyy-MM-dd")</td>
                <td>@current.Car.CarMark</td>
                <td>@current.Client.ClienFIO</td>
                <td>@current.RentPrice</td>
                <td>@current.Paid.ToString()</td>
                <td>@current.WorkerFIO</td>
                <td align="center" class="tdElem">
                    @using (Html.BeginForm("Editing", "Rent", FormMethod.Post, new { @class = "form-signin" }))
                    {
                        <input type="hidden" name="id" value="@current.RentID.ToString()" />
                        <input class="btn btn-success" type="submit" value="Edit" formaction="Edit" />
                        <input class="btn btn-danger" type="submit" value="Delete" formaction="Delete" onclick="return confirm('Are you sure, that you want to delete rent?');">
                    }
                </td>
            </tr>
        }
    </table>
    @lab2.Helpers.NavigationHelper.CreateNavigation(Html, "/Rent/Index", Model.PageViewModel)
    @using (@Html.BeginForm("AddNewRent", "Rent", FormMethod.Post))
    {

        Rent rent = (Rent)ViewData["AddingRent"];
        <input type="hidden" value="@rent.RentID" name="Id" />
        <div class="form-group">
            <label for="Clients">Select client</label>
            <select class="form-control" id="Client" name="Client">
                @{
                    List<Client> clients = (List<Client>)ViewData["Clients"];
                    foreach (var item in clients)
                    {
                        <option value=@item.Id>
                            @item.ClienFIO
                        </option>

                    }
                }
            </select>
        </div>
        <div class="form-group">
            <label for="Car">Select car</label>
            <select class="form-control" id="Car" name="Car">
                @{
                    List<Car> cars = (List<Car>)ViewData["Cars"];
                    foreach (var item in cars)
                    {
                        <option value=@item.CarID>
                            @item.CarMark @item.RegNum
                        </option>

                    }
                }
            </select>
        </div>
        <div class="form-group">
            <label for="RentDate">Input rent date</label>

            @Html.EditorFor(model => rent.RentDate)
        </div>
        <div class="form-group">
            <label for="DateGet">Input date get</label>

            @Html.EditorFor(model => rent.DateGet)
        </div>
        <div class="form-group">
            <label for="RentPrice">Input rent price</label>

            @Html.EditorFor(model => rent.RentPrice)
        </div>
        <div class="form-group">
            <label for="Paid">Input is paid</label>

            @Html.EditorFor(model => rent.Paid)
        </div>
        <div class="form-group">
            <label for="WorkerFIO">Input worker fio</label>

            @Html.EditorFor(model => rent.WorkerFIO)
        </div>
        <input type="submit" />

    }
</div>